import React from 'react';
import { AlertCircle } from 'lucide-react';

export const AIDisclaimer: React.FC = () => {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-xl p-3 flex items-start gap-3 mb-6 animate-in fade-in">
      <AlertCircle className="text-blue-600 shrink-0 mt-0.5" size={16} />
      <p className="text-xs text-blue-800 leading-relaxed">
        <strong>AI-Generated Content:</strong> This content was generated by AI and may contain inaccuracies. E^3 does not endorse any employer or guarantee partnership outcomes. All outputs require human review before use.
      </p>
    </div>
  );
};
